#!/usr/bin/env pwsh
#
# Troop 500G Build and Test Script - PDF Container First
# ======================================================
# 
# This script builds the PDF container first to ensure all dependencies are ready,
# then starts Jekyll. This approach resolves timing issues where Jekyll might fail
# if it expects certain files that are generated by the PDF container.
#

param(
    [switch]$NoCache,
    [switch]$SkipPDFs,
    [switch]$SkipTests,
    [switch]$Quick,
    [switch]$Help
)

if ($Help) {
    Write-Host @"
Troop 500G Build and Test Script - PDF Container First

USAGE:
    .\build_and_test_pdf_first.ps1 [OPTIONS]

OPTIONS:
    -NoCache     Force rebuild all containers without cache (slower but clean)
    -SkipPDFs    Skip PDF generation (faster for web-only changes)
    -SkipTests   Skip endpoint testing (faster for build-only runs)
    -Quick       Skip both PDFs and tests (fastest option)
    -Help        Show this help message

EXAMPLES:
    .\build_and_test_pdf_first.ps1                    # Full build with caching
    .\build_and_test_pdf_first.ps1 -Quick             # Fast web-only build
    .\build_and_test_pdf_first.ps1 -NoCache           # Clean full rebuild
    .\build_and_test_pdf_first.ps1 -SkipPDFs          # Web build with tests

This script follows a specific build order:
1. Build PDF container first (ensures dependencies are ready)
2. Generate PDFs if needed (creates any missing files Jekyll expects)
3. Build Jekyll container
4. Start Jekyll with all files in place
"@
    exit 0
}

# Set quick mode options
if ($Quick) {
    $SkipPDFs = $true
    $SkipTests = $true
}

Write-Host @"
Troop 500G Build and Test - PDF Container First
===============================================
Configuration:
  - Cache: $(if ($NoCache) { "Disabled (clean build)" } else { "Enabled (faster)" })
  - PDFs: $(if ($SkipPDFs) { "Skipped" } else { "Enabled" })
  - Tests: $(if ($SkipTests) { "Skipped" } else { "Enabled" })
  - Build Order: PDF container first, then Jekyll

"@ -ForegroundColor Cyan

# Function to test URL endpoints
function Test-Url {
    param($url, $description)
    try {
        $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 5
        if ($response.StatusCode -eq 200) {
            Write-Host "[PASS] $description" -ForegroundColor Green
            return $true
        } else {
            Write-Host "[FAIL] $description (Status: $($response.StatusCode))" -ForegroundColor Red
            return $false
        }
    } catch {
        Write-Host "[FAIL] $description (Error: $($_.Exception.Message))" -ForegroundColor Red
        return $false
    }
}

# Function to wait for Jekyll with exponential backoff
function Wait-ForJekyll {
    param($maxAttempts = 15)
    
    Write-Host "Waiting for Jekyll to start..." -ForegroundColor Yellow
    
    for ($i = 1; $i -le $maxAttempts; $i++) {
        # First check if Jekyll container is actually running
        try {
            $containerStatus = & $dockerComposeCmd.Split() ps --services --filter "status=running" 2>$null
            if ($containerStatus -notcontains "jekyll") {
                Write-Host "   Container check: Jekyll container is not running!" -ForegroundColor Red
                
                # Show container status for debugging
                Write-Host "   Current container status:" -ForegroundColor Yellow
                & $dockerComposeCmd.Split() ps jekyll
                
                # Show recent logs to understand what failed
                Write-Host "   Recent Jekyll container logs:" -ForegroundColor Yellow
                try {
                    $logs = & $dockerComposeCmd.Split() logs --tail=20 jekyll 2>&1
                    if ($logs) {
                        $logs | ForEach-Object { Write-Host "   $_" -ForegroundColor White }
                    } else {
                        Write-Host "   (No logs available)" -ForegroundColor Gray
                        
                        # Try alternative logging approach
                        Write-Host "   Trying docker logs directly..." -ForegroundColor Yellow
                        $containerName = & $dockerComposeCmd.Split() ps -q jekyll 2>$null
                        if ($containerName) {
                            $dockerLogs = & docker logs --tail=20 $containerName 2>&1
                            if ($dockerLogs) {
                                $dockerLogs | ForEach-Object { Write-Host "   $_" -ForegroundColor White }
                            } else {
                                Write-Host "   (No direct docker logs available)" -ForegroundColor Gray
                            }
                        }
                    }
                } catch {
                    Write-Host "   Error retrieving logs: $($_.Exception.Message)" -ForegroundColor Red
                }
                
                Write-Host "FAIL - Jekyll container failed to start or crashed" -ForegroundColor Red
                return $false
            }
            
            Write-Host "   Container check: Jekyll container is running" -ForegroundColor Green
        } catch {
            Write-Host "   Container check: Could not verify container status" -ForegroundColor Yellow
        }
        
        # Now test HTTP endpoint
        try {
            $response = Invoke-WebRequest -Uri "http://localhost:4000" -UseBasicParsing -TimeoutSec 2
            if ($response.StatusCode -eq 200) {
                Write-Host "PASS - Jekyll is ready!" -ForegroundColor Green
                return $true
            }
        } catch {
            # Expected when Jekyll isn't ready yet
            Write-Host "   HTTP check: Jekyll not responding yet ($($_.Exception.Message))" -ForegroundColor Yellow
        }
        
        # Exponential backoff: 2s, 4s, 8s, then 8s max
        $sleepTime = [Math]::Min(8, [Math]::Pow(2, $i))
        Write-Host "   Attempt $i/$maxAttempts - waiting ${sleepTime}s..." -ForegroundColor Yellow
        Start-Sleep -Seconds $sleepTime
    }
    
    Write-Host "FAIL - Jekyll failed to start after $maxAttempts attempts" -ForegroundColor Red
    return $false
}

# Start timer
$startTime = Get-Date

# Step 1: Prerequisites check
Write-Host "Checking prerequisites..." -ForegroundColor Cyan
$dockerComposeCmd = if (Get-Command docker-compose -ErrorAction SilentlyContinue) { "docker-compose" } else { "docker compose" }

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "FAIL - Docker not found" -ForegroundColor Red
    exit 1
}

Write-Host "Prerequisites check passed" -ForegroundColor Green

# Step 2: Clean and prepare
Write-Host "`nCleaning up..." -ForegroundColor Cyan

# Stop any running containers
& $dockerComposeCmd.Split() down 2>$null

# Clean up old files if not in quick mode
if (-not $Quick) {
    if (Test-Path "_site") {
        Remove-Item -Path "_site" -Recurse -Force
        Write-Host "Cleaned up _site directory" -ForegroundColor Green
    }
}

# Ensure PDF directories exist
@("assets/files/handbook", "assets/files/handbook/archive") | ForEach-Object {
    if (!(Test-Path $_)) {
        New-Item -Path $_ -ItemType Directory -Force | Out-Null
    }
}

Write-Host "PDF directories ready" -ForegroundColor Green

# Step 3: Build PDF container first
Write-Host "`nBuilding PDF container..." -ForegroundColor Cyan
$pdfBuildArgs = $dockerComposeCmd.Split() + @("build")
if ($NoCache) {
    $pdfBuildArgs += "--no-cache"
    Write-Host "Using --no-cache for clean PDF container build" -ForegroundColor Yellow
} else {
    Write-Host "Using cached layers for PDF container" -ForegroundColor Green
}
$pdfBuildArgs += "pdf-generator"

& $pdfBuildArgs[0] $pdfBuildArgs[1..($pdfBuildArgs.Length-1)]
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAIL - PDF container build failed" -ForegroundColor Red
    exit 1
}

$pdfBuildTime = (Get-Date) - $startTime
Write-Host "PASS - PDF container built successfully ($([Math]::Round($pdfBuildTime.TotalSeconds, 1))s)" -ForegroundColor Green

# Step 4: Generate PDFs if needed (before Jekyll starts)
if (-not $SkipPDFs) {
    Write-Host "`nGenerating PDFs before Jekyll startup..." -ForegroundColor Cyan
    
    # Generate PDFs synchronously to ensure files are ready
    $pdfArgs = $dockerComposeCmd.Split() + @("run", "--rm", "pdf-generator")
    & $pdfArgs[0] $pdfArgs[1..($pdfArgs.Length-1)]
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "PASS - PDF generation completed successfully!" -ForegroundColor Green
        
        # Update latest PDF files from newly generated timestamped versions
        Write-Host "Updating latest PDF files from newly generated versions..." -ForegroundColor Yellow
        
        $pdfTypes = @("troop-handbook", "contact-info")
        foreach ($pdfType in $pdfTypes) {
            $mostRecentPDF = Get-ChildItem "assets/files/handbook/$pdfType-20*.pdf" -ErrorAction SilentlyContinue | 
                             Sort-Object LastWriteTime -Descending | 
                             Select-Object -First 1
            
            $latestPath = "assets/files/handbook/$pdfType-latest.pdf"
            
            if ($mostRecentPDF) {
                # Remove existing latest file if it exists
                if (Test-Path $latestPath) {
                    Remove-Item $latestPath -Force
                }
                
                Copy-Item $mostRecentPDF.FullName $latestPath
                $sizeKB = [Math]::Round($mostRecentPDF.Length / 1024, 1)
                Write-Host "PASS - Updated $pdfType-latest.pdf from $($mostRecentPDF.Name) ($sizeKB KB)" -ForegroundColor Green
            } else {
                Write-Host "WARN - No timestamped $pdfType PDF found to copy" -ForegroundColor Yellow
            }
        }
        
        # Update handbook page with cache-busting timestamp
        Write-Host "Updating handbook page with cache-busting parameters..." -ForegroundColor Yellow
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $handbookPath = "pages/handbook.md"
        
        if (Test-Path $handbookPath) {
            $content = Get-Content $handbookPath -Raw
            
            # Update PDF links with cache-busting parameters
            $content = $content -replace 
                '\[2025 Troop Handbook\]\(/assets/files/handbook/troop-handbook-latest\.pdf[^)]*\)', 
                "[2025 Troop Handbook](/assets/files/handbook/troop-handbook-latest.pdf?v=$timestamp)"
            
            $content = $content -replace 
                '\[Contact Directory\]\(/assets/files/handbook/contact-info-latest\.pdf[^)]*\)', 
                "[Contact Directory](/assets/files/handbook/contact-info-latest.pdf?v=$timestamp)"
            
            Set-Content -Path $handbookPath -Value $content -NoNewline
            Write-Host "PASS - Updated handbook page with cache-busting timestamp: $timestamp" -ForegroundColor Green
        } else {
            Write-Host "WARN - handbook.md not found, skipping cache-busting update" -ForegroundColor Yellow
        }
    } else {
        Write-Host "FAIL - PDF generation failed" -ForegroundColor Red
        Write-Host "Continuing with Jekyll build anyway..." -ForegroundColor Yellow
    }
} else {
    Write-Host "`nSkipping PDF generation (will ensure latest files exist)" -ForegroundColor Yellow
    
    # Even when skipping PDF generation, ensure latest files exist from previous runs
    Write-Host "Ensuring latest PDF files exist from previous generations..." -ForegroundColor Yellow
    
    $pdfTypes = @("troop-handbook", "contact-info")
    foreach ($pdfType in $pdfTypes) {
        $latestPath = "assets/files/handbook/$pdfType-latest.pdf"
        
        if (-not (Test-Path $latestPath)) {
            # Find most recent timestamped PDF to use as latest
            $mostRecentPDF = Get-ChildItem "assets/files/handbook/$pdfType-20*.pdf" -ErrorAction SilentlyContinue | 
                             Sort-Object LastWriteTime -Descending | 
                             Select-Object -First 1
            
            if ($mostRecentPDF) {
                Copy-Item $mostRecentPDF.FullName $latestPath
                $sizeKB = [Math]::Round($mostRecentPDF.Length / 1024, 1)
                Write-Host "PASS - Created $pdfType-latest.pdf from $($mostRecentPDF.Name) ($sizeKB KB)" -ForegroundColor Green
            } else {
                # Create minimal placeholder if no PDFs exist
                $pdfContent = @"
%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >>
endobj
xref
0 4
0000000000 65535 f 
0000000010 00000 n 
0000000056 00000 n 
0000000111 00000 n 
trailer
<< /Size 4 /Root 1 0 R >>
startxref
180
%%EOF
"@
                $pdfContent | Out-File -FilePath $latestPath -Encoding ASCII -NoNewline
                Write-Host "WARN - Created minimal placeholder for $pdfType-latest.pdf (no previous generation found)" -ForegroundColor Yellow
            }
        } else {
            $existingSize = [Math]::Round((Get-Item $latestPath).Length / 1024, 1)
            Write-Host "PASS - $pdfType-latest.pdf already exists ($existingSize KB)" -ForegroundColor Green
        }
    }
}

# Step 5: Build Jekyll container
Write-Host "`nBuilding Jekyll container..." -ForegroundColor Cyan
$jekyllBuildArgs = $dockerComposeCmd.Split() + @("build")
if ($NoCache) {
    $jekyllBuildArgs += "--no-cache"
    Write-Host "Using --no-cache for clean Jekyll container build" -ForegroundColor Yellow
} else {
    Write-Host "Using cached layers for Jekyll container" -ForegroundColor Green
}
$jekyllBuildArgs += "jekyll"

& $jekyllBuildArgs[0] $jekyllBuildArgs[1..($jekyllBuildArgs.Length-1)]
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAIL - Jekyll container build failed" -ForegroundColor Red
    exit 1
}

$jekyllBuildTime = (Get-Date) - $startTime
Write-Host "PASS - Jekyll container built successfully ($([Math]::Round($jekyllBuildTime.TotalSeconds, 1))s total)" -ForegroundColor Green

# Step 6: Start Jekyll
Write-Host "`nStarting Jekyll..." -ForegroundColor Cyan
$startArgs = $dockerComposeCmd.Split() + @("up", "-d", "jekyll")
& $startArgs[0] $startArgs[1..($startArgs.Length-1)]
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAIL - Failed to start Jekyll" -ForegroundColor Red
    exit 1
}

# Wait for Jekyll to be ready
if (-not (Wait-ForJekyll)) {
    Write-Host "FAIL - Build failed - Jekyll startup timeout" -ForegroundColor Red
    
    # Show recent logs for debugging
    Write-Host "`nRecent Jekyll logs (final check):" -ForegroundColor Yellow
    try {
        $logs = & $dockerComposeCmd.Split() logs --tail=30 jekyll 2>&1
        if ($logs) {
            $logs | ForEach-Object { Write-Host "$_" -ForegroundColor White }
        } else {
            Write-Host "(No logs available via docker-compose)" -ForegroundColor Gray
            
            # Try direct docker logs
            $containerName = & $dockerComposeCmd.Split() ps -q jekyll 2>$null
            if ($containerName) {
                Write-Host "Trying direct docker logs..." -ForegroundColor Yellow
                $dockerLogs = & docker logs --tail=30 $containerName 2>&1
                if ($dockerLogs) {
                    $dockerLogs | ForEach-Object { Write-Host "$_" -ForegroundColor White }
                } else {
                    Write-Host "(No direct docker logs available)" -ForegroundColor Gray
                }
            }
        }
    } catch {
        Write-Host "Error retrieving logs: $($_.Exception.Message)" -ForegroundColor Red
    }
    
    # Show container status
    Write-Host "`nFinal container status:" -ForegroundColor Yellow
    & $dockerComposeCmd.Split() ps
    
    exit 1
}

$startupTime = (Get-Date) - $startTime
Write-Host "PASS - Jekyll started successfully ($([Math]::Round($startupTime.TotalSeconds, 1))s total)" -ForegroundColor Green

# Step 7: Test website (if not skipped)
if (-not $SkipTests) {
    Write-Host "`nTesting website endpoints..." -ForegroundColor Cyan
    $failedTests = 0
    
    # Core pages (run in parallel for speed)
    $testJobs = @()
    $tests = @(
        @{ Url = "http://localhost:4000"; Name = "Homepage" },
        @{ Url = "http://localhost:4000/handbook"; Name = "Handbook page" },
        @{ Url = "http://localhost:4000/about"; Name = "About page" },
        @{ Url = "http://localhost:4000/events"; Name = "Events page" }
    )
    
    foreach ($test in $tests) {
        $testJobs += Start-Job -ScriptBlock {
            param($url, $name)
            try {
                $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 10
                return @{ Success = ($response.StatusCode -eq 200); Name = $name; Status = $response.StatusCode }
            } catch {
                return @{ Success = $false; Name = $name; Error = $_.Exception.Message }
            }
        } -ArgumentList $test.Url, $test.Name
    }
    
    # Wait for all tests and report results
    foreach ($job in $testJobs) {
        $result = Receive-Job -Job $job -Wait
        if ($result.Success) {
            Write-Host "[PASS] $($result.Name)" -ForegroundColor Green
        } else {
            Write-Host "[FAIL] $($result.Name)" -ForegroundColor Red
            $failedTests++
        }
    }
    $testJobs | Remove-Job -Force
    
    # Test PDF files (if they were generated)
    if (-not $SkipPDFs) {
        if (-not (Test-Url "http://localhost:4000/assets/files/handbook/troop-handbook-latest.pdf" "Latest handbook PDF")) { $failedTests++ }
        if (-not (Test-Url "http://localhost:4000/assets/files/handbook/contact-info-latest.pdf" "Latest contact info PDF")) { $failedTests++ }
    }
    
    # Report test results
    Write-Host ""
    if ($failedTests -eq 0) {
        Write-Host "PASS - All tests passed!" -ForegroundColor Green
    } else {
        Write-Host "FAIL - $failedTests test(s) failed" -ForegroundColor Red
    }
} else {
    Write-Host "`nSkipping endpoint tests" -ForegroundColor Yellow
    $failedTests = 0
}

# Final summary
$totalTime = (Get-Date) - $startTime
Write-Host @"

Build Summary
=============
Total time: $([Math]::Round($totalTime.TotalMinutes, 1)) minutes
Build type: $(if ($NoCache) { "Clean (no cache)" } else { "Incremental (cached)" })
Build order: PDF container first, then Jekyll
PDFs: $(if ($SkipPDFs) { "Skipped" } else { "Generated" })
Tests: $(if ($SkipTests) { "Skipped" } else { if ($failedTests -eq 0) { "PASS" } else { "FAIL ($failedTests failed)" } })

Jekyll is running at: http://localhost:4000
Container status:
"@ -ForegroundColor Cyan

& $dockerComposeCmd.Split() ps

if ($failedTests -eq 0) {
    Write-Host "`nSUCCESS - Build completed successfully!" -ForegroundColor Green
    exit 0
} else {
    Write-Host "`nWARNING - Build completed with issues" -ForegroundColor Yellow
    exit 1
}
