#!/usr/bin/env pwsh
#
# Troop 500G Build and Test Script - PDF Container First
# ======================================================
# 
# This script builds the PDF container first to ensure all dependencies are ready,
# then starts Jekyll. This approach resolves timing issues where Jekyll might fail
# if it expects certain files that are generated by the PDF container.
#

param(
    [switch]$NoCache,
    [switch]$SkipPDFs,
    [switch]$SkipTests,
    [switch]$Quick,
    [string]$IssuesFile = "test-issues-summary.md",
    [switch]$Help
)

if ($Help) {
    Write-Host @"
Troop 500G Build and Test Script - PDF Container First

USAGE:
    .\build_and_test_pdf_first.ps1 [OPTIONS]

OPTIONS:
    -NoCache     Force rebuild all containers without cache (slower but clean)
    -SkipPDFs    Skip PDF generation (faster for web-only changes)
    -SkipTests   Skip endpoint testing (faster for build-only runs)
    -Quick       Skip both PDFs and tests (fastest option)
    -IssuesFile  Path for consolidated issues report (default: test-issues-summary.md)
    -Help        Show this help message

EXAMPLES:
    .\build_and_test_pdf_first.ps1                    # Full build with caching
    .\build_and_test_pdf_first.ps1 -Quick             # Fast web-only build
    .\build_and_test_pdf_first.ps1 -NoCache           # Clean full rebuild
    .\build_and_test_pdf_first.ps1 -SkipPDFs          # Web build with tests

This script follows a specific build order:
1. Build PDF container first (ensures dependencies are ready)
2. Generate PDFs if needed (creates any missing files Jekyll expects)
3. Build Jekyll container
4. Start Jekyll with all files in place
5. Run comprehensive test suite and generate consolidated issue report

Issues are consolidated into a single Markdown file for LLM review and correction.
"@
    exit 0
}

# Set quick mode options
if ($Quick) {
    $SkipPDFs = $true
    $SkipTests = $true
}

# Import test modules (cross-platform paths)
. (Join-Path $PSScriptRoot (Join-Path "test" "test-self-urls.ps1"))
. (Join-Path $PSScriptRoot (Join-Path "test" "test-external-links.ps1"))
. (Join-Path $PSScriptRoot (Join-Path "test" "test-pdf-links.ps1"))
. (Join-Path $PSScriptRoot (Join-Path "test" "test-appendix-pdfs.ps1"))
. (Join-Path $PSScriptRoot (Join-Path "test" "test-linux-compatibility.ps1"))
. (Join-Path $PSScriptRoot (Join-Path "utils" "jekyll-service.ps1"))

# Error tracking for consolidated reporting
$Global:IssueCount = 0
$Global:AllIssues = @()

function Add-Issue {
    param(
        [string]$Category,
        [string]$Issue,
        [string]$Details = "",
        [string]$Severity = "Warning"
    )
    
    $Global:IssueCount++
    $IssueEntry = [PSCustomObject]@{
        Number = $Global:IssueCount
        Category = $Category
        Severity = $Severity
        Issue = $Issue
        Details = $Details
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    }
    $Global:AllIssues += $IssueEntry
    
    # Also write to console for immediate feedback
    Write-Warning "[$Category] $Issue $(if($Details) { "- $Details" })"
}

function Write-ConsolidatedReport {
    param([string]$ReportPath)
    
    $ReportContent = @"
# Build and Test Issues Report

Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
Total Issues Found: $($Global:AllIssues.Count)

"@

    if ($Global:AllIssues.Count -eq 0) {
        $ReportContent += @"

## Summary
✅ **All tests passed successfully!** No issues were detected during the build and test process.

"@
    } else {
        # Group issues by category for better organization
        $GroupedIssues = $Global:AllIssues | Group-Object Category
        
        $ReportContent += @"

## Summary by Category

"@
        foreach ($Group in $GroupedIssues) {
            $ErrorCount = ($Group.Group | Where-Object { $_.Severity -eq "Error" }).Count
            $WarningCount = ($Group.Group | Where-Object { $_.Severity -eq "Warning" }).Count
            $ReportContent += "- **$($Group.Name)**: $($Group.Count) issues ($ErrorCount errors, $WarningCount warnings)`n"
        }
        
        $ReportContent += @"

## Detailed Issues

"@
        
        foreach ($Group in $GroupedIssues) {
            $ReportContent += @"

### $($Group.Name)

"@
            foreach ($Issue in $Group.Group) {
                $SeverityIcon = if ($Issue.Severity -eq "Error") { "❌" } else { "⚠️" }
                $ReportContent += @"
$SeverityIcon **Issue #$($Issue.Number)**: $($Issue.Issue)
$(if($Issue.Details) { "   - Details: $($Issue.Details)" })
   - Time: $($Issue.Timestamp)

"@
            }
        }
        
        $ReportContent += @"

## Recommendations for LLM Review

This report contains all issues found during the build and test process. Each issue includes:
- Category (area of concern)
- Severity level (Error/Warning)
- Detailed description
- Timestamp for tracking

For LLM analysis, please focus on:
1. **Errors** (❌) - These require immediate attention
2. **Warnings** (⚠️) - These should be reviewed for potential improvements
3. **Patterns** - Look for recurring issues across categories
4. **Dependencies** - Consider how issues might be related

"@
    }
    
    try {
        $ReportContent | Out-File -FilePath $ReportPath -Encoding UTF8 -Force
        Write-Host "📊 Consolidated issues report written to: $ReportPath" -ForegroundColor Green
        if ($Global:AllIssues.Count -gt 0) {
            Write-Host "   Found $($Global:AllIssues.Count) total issues for review" -ForegroundColor Yellow
        }
    } catch {
        Write-Error "Failed to write issues report to $ReportPath`: $_"
    }
}

# Helper function to safely replace a file that might be locked by another process
function Copy-FileWithRetry {
    param(
        [string]$SourcePath,
        [string]$DestinationPath,
        [int]$MaxRetries = 5,
        [int]$RetryDelaySeconds = 2
    )
    
    $attempt = 1
    while ($attempt -le $MaxRetries) {
        try {
            # Try to remove existing file if it exists
            if (Test-Path $DestinationPath) {
                Remove-Item $DestinationPath -Force -ErrorAction Stop
            }
            
            # Copy the new file
            Copy-Item $SourcePath $DestinationPath -Force -ErrorAction Stop
            return $true
        }
        catch {
            Write-Host "Attempt $attempt failed: $($_.Exception.Message)" -ForegroundColor Yellow
            
            if ($attempt -eq $MaxRetries) {
                $platform = if ($IsWindows) { "Windows" } elseif ($IsLinux) { "Linux" } elseif ($IsMacOS) { "macOS" } else { "Unknown" }
                Write-Host "Failed to copy file after $MaxRetries attempts on $platform." -ForegroundColor Red
                if ($IsWindows) {
                    Write-Host "File may be locked by another process. Please close any PDF viewers or browsers that might have the file open and try again." -ForegroundColor Red
                } else {
                    Write-Host "Check file permissions and ensure the destination directory is writable." -ForegroundColor Red
                }
                return $false
            }
            
            Write-Host "Retrying in $RetryDelaySeconds seconds..." -ForegroundColor Yellow
            Start-Sleep -Seconds $RetryDelaySeconds
            $attempt++
        }
    }
}

Write-Host @"
Troop 500G Build and Test - PDF Container First
===============================================
Configuration:
  - Cache: $(if ($NoCache) { "Disabled (clean build)" } else { "Enabled (faster)" })
  - PDFs: $(if ($SkipPDFs) { "Skipped" } else { "Enabled" })
  - Tests: $(if ($SkipTests) { "Skipped" } else { "Enabled" })
  - Build Order: PDF container first, then Jekyll

"@ -ForegroundColor Cyan

# Start timer
$startTime = Get-Date

# Step 1: Prerequisites check
Write-Host "Checking prerequisites..." -ForegroundColor Cyan
$dockerComposeCmd = if (Get-Command docker-compose -ErrorAction SilentlyContinue) { "docker-compose" } else { "docker compose" }

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "FAIL - Docker not found" -ForegroundColor Red
    exit 1
}

Write-Host "Prerequisites check passed" -ForegroundColor Green

# Step 2: Clean and prepare
Write-Host "`nCleaning up..." -ForegroundColor Cyan

# Stop any running containers
& $dockerComposeCmd.Split() down 2>$null

# Clean up old files if not in quick mode
if (-not $Quick) {
    if (Test-Path "_site") {
        Remove-Item -Path "_site" -Recurse -Force
        Write-Host "Cleaned up _site directory" -ForegroundColor Green
    }
}

# Ensure PDF directories exist
@("assets/files/handbook", "assets/files/handbook/archive", "assets/files/handbook/appendix", "assets/files/handbook/appendix/archive") | ForEach-Object {
    if (!(Test-Path $_)) {
        New-Item -Path $_ -ItemType Directory -Force | Out-Null
    }
}

Write-Host "PDF directories ready" -ForegroundColor Green

# Step 3: Build PDF container first
Write-Host "`nBuilding PDF container..." -ForegroundColor Cyan
$pdfBuildArgs = $dockerComposeCmd.Split() + @("build")
if ($NoCache) {
    $pdfBuildArgs += "--no-cache"
    Write-Host "Using --no-cache for clean PDF container build" -ForegroundColor Yellow
} else {
    Write-Host "Using cached layers for PDF container" -ForegroundColor Green
}
$pdfBuildArgs += "pdf-generator"

& $pdfBuildArgs[0] $pdfBuildArgs[1..($pdfBuildArgs.Length-1)]
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAIL - PDF container build failed" -ForegroundColor Red
    exit 1
}

$pdfBuildTime = (Get-Date) - $startTime
Write-Host "PASS - PDF container built successfully ($([Math]::Round($pdfBuildTime.TotalSeconds, 1))s)" -ForegroundColor Green

# Step 4: Generate PDFs if needed (before Jekyll starts)
if (-not $SkipPDFs) {
    Write-Host "`nGenerating PDFs before Jekyll startup..." -ForegroundColor Cyan
    
    # Generate PDFs synchronously to ensure files are ready
    $pdfArgs = $dockerComposeCmd.Split() + @("run", "--rm", "pdf-generator")
    & $pdfArgs[0] $pdfArgs[1..($pdfArgs.Length-1)]
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "PASS - PDF generation completed successfully!" -ForegroundColor Green
        
        # Update latest PDF files from newly generated timestamped versions
        Write-Host "Updating latest PDF files from newly generated versions..." -ForegroundColor Yellow
        
        $pdfTypes = @("troop-handbook", "contact-info")
        foreach ($pdfType in $pdfTypes) {
            $mostRecentPDF = Get-ChildItem "assets/files/handbook/$pdfType-20*.pdf" -ErrorAction SilentlyContinue | 
                             Sort-Object LastWriteTime -Descending | 
                             Select-Object -First 1
            
            $latestPath = "assets/files/handbook/$pdfType-latest.pdf"
            
            if ($mostRecentPDF) {
                # Use the retry function for safer file operations
                if (Copy-FileWithRetry -SourcePath $mostRecentPDF.FullName -DestinationPath $latestPath) {
                    $sizeKB = [Math]::Round($mostRecentPDF.Length / 1024, 1)
                    Write-Host "PASS - Updated $pdfType-latest.pdf from $($mostRecentPDF.Name) ($sizeKB KB)" -ForegroundColor Green
                } else {
                    Write-Host "FAIL - Could not update $pdfType-latest.pdf (file may be locked)" -ForegroundColor Red
                }
            } else {
                Write-Host "WARN - No timestamped $pdfType PDF found to copy" -ForegroundColor Yellow
            }
        }
        
        # Update appendix PDF latest files
        Write-Host "Updating appendix PDF latest files..." -ForegroundColor Yellow
        $appendixDir = "assets/files/handbook/appendix"
        if (Test-Path $appendixDir) {
            $appendixMdFiles = Get-ChildItem "_includes/content/appendix/*.md" -ErrorAction SilentlyContinue
            foreach ($mdFile in $appendixMdFiles) {
                $baseName = $mdFile.BaseName
                $mostRecentAppendixPDF = Get-ChildItem "$appendixDir/$baseName-20*.pdf" -ErrorAction SilentlyContinue | 
                                       Sort-Object LastWriteTime -Descending | 
                                       Select-Object -First 1
                
                $latestAppendixPath = "$appendixDir/$baseName-latest.pdf"
                
                if ($mostRecentAppendixPDF) {
                    # Use the retry function for safer file operations
                    if (Copy-FileWithRetry -SourcePath $mostRecentAppendixPDF.FullName -DestinationPath $latestAppendixPath) {
                        $sizeKB = [Math]::Round($mostRecentAppendixPDF.Length / 1024, 1)
                        Write-Host "PASS - Updated appendix $baseName-latest.pdf from $($mostRecentAppendixPDF.Name) ($sizeKB KB)" -ForegroundColor Green
                    } else {
                        Write-Host "FAIL - Could not update appendix $baseName-latest.pdf (file may be locked)" -ForegroundColor Red
                    }
                } else {
                    Write-Host "WARN - No timestamped appendix PDF found for $baseName" -ForegroundColor Yellow
                }
            }
        }
        
        # Update handbook page with cache-busting timestamp
        Write-Host "Updating handbook page with cache-busting parameters..." -ForegroundColor Yellow
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $handbookPath = "pages/handbook.md"
        
        if (Test-Path $handbookPath) {
            $content = Get-Content $handbookPath -Raw
            
            # Update PDF links with cache-busting parameters
            $content = $content -replace 
                '\[2025 Troop Handbook\]\(/assets/files/handbook/troop-handbook-latest\.pdf[^)]*\)', 
                "[2025 Troop Handbook](/assets/files/handbook/troop-handbook-latest.pdf?v=$timestamp)"
            
            $content = $content -replace 
                '\[Contact Directory\]\(/assets/files/handbook/appendix/contact-info-latest\.pdf[^)]*\)', 
                "[Contact Directory](/assets/files/handbook/appendix/contact-info-latest.pdf?v=$timestamp)"
            
            Set-Content -Path $handbookPath -Value $content -NoNewline
            Write-Host "PASS - Updated handbook page with cache-busting timestamp: $timestamp" -ForegroundColor Green
        } else {
            Write-Host "WARN - handbook.md not found, skipping cache-busting update" -ForegroundColor Yellow
        }
    } else {
        Write-Host "FAIL - PDF generation failed" -ForegroundColor Red
        Write-Host "Continuing with Jekyll build anyway..." -ForegroundColor Yellow
    }
} else {
    Write-Host "`nSkipping PDF generation (will ensure latest files exist)" -ForegroundColor Yellow
    
    # Even when skipping PDF generation, ensure latest files exist from previous runs
    Write-Host "Ensuring latest PDF files exist from previous generations..." -ForegroundColor Yellow
    
    $pdfTypes = @("troop-handbook", "contact-info")
    foreach ($pdfType in $pdfTypes) {
        $latestPath = "assets/files/handbook/$pdfType-latest.pdf"
        
        if (-not (Test-Path $latestPath)) {
            # Find most recent timestamped PDF to use as latest
            $mostRecentPDF = Get-ChildItem "assets/files/handbook/$pdfType-20*.pdf" -ErrorAction SilentlyContinue | 
                             Sort-Object LastWriteTime -Descending | 
                             Select-Object -First 1
            
            if ($mostRecentPDF) {
                if (Copy-FileWithRetry -SourcePath $mostRecentPDF.FullName -DestinationPath $latestPath) {
                    $sizeKB = [Math]::Round($mostRecentPDF.Length / 1024, 1)
                    Write-Host "PASS - Created $pdfType-latest.pdf from $($mostRecentPDF.Name) ($sizeKB KB)" -ForegroundColor Green
                } else {
                    Write-Host "FAIL - Could not create $pdfType-latest.pdf (file may be locked)" -ForegroundColor Red
                }
            } else {
                # Create minimal placeholder if no PDFs exist
                $pdfContent = @"
%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >>
endobj
xref
0 4
0000000000 65535 f 
0000000010 00000 n 
0000000056 00000 n 
0000000111 00000 n 
trailer
<< /Size 4 /Root 1 0 R >>
startxref
180
%%EOF
"@
                $pdfContent | Out-File -FilePath $latestPath -Encoding ASCII -NoNewline
                Write-Host "WARN - Created minimal placeholder for $pdfType-latest.pdf (no previous generation found)" -ForegroundColor Yellow
            }
        } else {
            $existingSize = [Math]::Round((Get-Item $latestPath).Length / 1024, 1)
            Write-Host "PASS - $pdfType-latest.pdf already exists ($existingSize KB)" -ForegroundColor Green
        }
    }
    
    # Also ensure appendix PDF latest files exist when skipping generation
    Write-Host "Ensuring appendix PDF latest files exist..." -ForegroundColor Yellow
    $appendixDir = "assets/files/handbook/appendix"
    if (Test-Path $appendixDir) {
        $appendixMdFiles = Get-ChildItem "_includes/content/appendix/*.md" -ErrorAction SilentlyContinue
        foreach ($mdFile in $appendixMdFiles) {
            $baseName = $mdFile.BaseName
            $latestAppendixPath = "$appendixDir/$baseName-latest.pdf"
            
            if (-not (Test-Path $latestAppendixPath)) {
                # Find most recent timestamped appendix PDF to use as latest
                $mostRecentAppendixPDF = Get-ChildItem "$appendixDir/$baseName-20*.pdf" -ErrorAction SilentlyContinue | 
                                       Sort-Object LastWriteTime -Descending | 
                                       Select-Object -First 1
                
                if ($mostRecentAppendixPDF) {
                    if (Copy-FileWithRetry -SourcePath $mostRecentAppendixPDF.FullName -DestinationPath $latestAppendixPath) {
                        $sizeKB = [Math]::Round($mostRecentAppendixPDF.Length / 1024, 1)
                        Write-Host "PASS - Created appendix $baseName-latest.pdf from $($mostRecentAppendixPDF.Name) ($sizeKB KB)" -ForegroundColor Green
                    } else {
                        Write-Host "FAIL - Could not create appendix $baseName-latest.pdf (file may be locked)" -ForegroundColor Red
                    }
                } else {
                    Write-Host "WARN - No previous appendix PDF found for $baseName" -ForegroundColor Yellow
                }
            } else {
                $existingSize = [Math]::Round((Get-Item $latestAppendixPath).Length / 1024, 1)
                Write-Host "PASS - Appendix $baseName-latest.pdf already exists ($existingSize KB)" -ForegroundColor Green
            }
        }
    }
}

# Step 5: Build Jekyll container
Write-Host "`nBuilding Jekyll container..." -ForegroundColor Cyan
$jekyllBuildArgs = $dockerComposeCmd.Split() + @("build")
if ($NoCache) {
    $jekyllBuildArgs += "--no-cache"
    Write-Host "Using --no-cache for clean Jekyll container build" -ForegroundColor Yellow
} else {
    Write-Host "Using cached layers for Jekyll container" -ForegroundColor Green
}
$jekyllBuildArgs += "jekyll"

& $jekyllBuildArgs[0] $jekyllBuildArgs[1..($jekyllBuildArgs.Length-1)]
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAIL - Jekyll container build failed" -ForegroundColor Red
    exit 1
}

$jekyllBuildTime = (Get-Date) - $startTime
Write-Host "PASS - Jekyll container built successfully ($([Math]::Round($jekyllBuildTime.TotalSeconds, 1))s total)" -ForegroundColor Green

# Step 6: Start Jekyll
Write-Host "`nStarting Jekyll..." -ForegroundColor Cyan
$startArgs = $dockerComposeCmd.Split() + @("up", "-d", "jekyll")
& $startArgs[0] $startArgs[1..($startArgs.Length-1)]
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAIL - Failed to start Jekyll" -ForegroundColor Red
    exit 1
}

# Wait for Jekyll to be ready
if (-not (Wait-ForJekyll -TimeoutSec 120)) {
    Write-Host "FAIL - Build failed - Jekyll startup timeout" -ForegroundColor Red
    
    # Show recent logs for debugging
    Write-Host "`nRecent Jekyll logs (final check):" -ForegroundColor Yellow
    try {
        $logs = & $dockerComposeCmd.Split() logs --tail=30 jekyll 2>&1
        if ($logs) {
            $logs | ForEach-Object { Write-Host "$_" -ForegroundColor White }
        } else {
            Write-Host "(No logs available via docker-compose)" -ForegroundColor Gray
            
            # Try direct docker logs
            $containerName = & $dockerComposeCmd.Split() ps -q jekyll 2>$null
            if ($containerName) {
                Write-Host "Trying direct docker logs..." -ForegroundColor Yellow
                $dockerLogs = & docker logs --tail=30 $containerName 2>&1
                if ($dockerLogs) {
                    $dockerLogs | ForEach-Object { Write-Host "$_" -ForegroundColor White }
                } else {
                    Write-Host "(No direct docker logs available)" -ForegroundColor Gray
                }
            }
        }
    } catch {
        Write-Host "Error retrieving logs: $($_.Exception.Message)" -ForegroundColor Red
    }
    
    # Show container status
    Write-Host "`nFinal container status:" -ForegroundColor Yellow
    & $dockerComposeCmd.Split() ps
    
    exit 1
}

$startupTime = (Get-Date) - $startTime
Write-Host "PASS - Jekyll started successfully ($([Math]::Round($startupTime.TotalSeconds, 1))s total)" -ForegroundColor Green

# Step 7: Test website (if not skipped)
if (-not $SkipTests) {
    Write-Host "`nRunning comprehensive test suite..." -ForegroundColor Cyan
    
    # Initialize issues tracking
    $Global:IssueCount = 0
    $Global:AllIssues = @()
    
    # Test self URLs (internal links)
    Write-Host "Testing self URLs..." -ForegroundColor Yellow
    try {
        $selfUrlResults = Test-StandardWebsiteEndpoints -BaseUrl "http://localhost:4000"
        if ($selfUrlResults -gt 0) {
            Add-Issue "Self URLs" "Internal URL failures detected" "$selfUrlResults URL(s) failed testing" "Error"
        }
    } catch {
        Add-Issue "Self URLs" "Test execution failed" $_.Exception.Message "Error"
    }
    
    # Test external links
    Write-Host "Testing external links..." -ForegroundColor Yellow
    try {
        $externalResults = Test-ExternalLinksFromWebsite -BaseUrl "http://localhost:4000" -ReportIssues
        if ($externalResults.FailedLinks -gt 0) {
            Add-Issue "External Links" "External link failures detected" "$($externalResults.FailedLinks) external link(s) failed out of $($externalResults.TotalLinks) total" "Error"
        }
    } catch {
        Add-Issue "External Links" "Test execution failed" $_.Exception.Message "Error"
    }
    
    # Test PDF links (if PDFs were generated)
    if (-not $SkipPDFs) {
        Write-Host "Testing PDF links..." -ForegroundColor Yellow
        try {
            $pdfResults = Test-LinksInPdfs -PdfDirectory (Join-Path $PSScriptRoot "..\assets\files\handbook")
            if ($pdfResults.FailedLinks -gt 0) {
                Add-Issue "PDF Links" "PDF link failures detected" "$($pdfResults.FailedLinks) PDF link(s) failed out of $($pdfResults.TotalLinks) total" "Error"
            }
        } catch {
            Add-Issue "PDF Links" "Test execution failed" $_.Exception.Message "Error"
        }
        
        # Test appendix PDFs
        Write-Host "Testing appendix PDFs..." -ForegroundColor Yellow
        try {
            $appendixResults = Test-AppendixPDFs -BaseDir (Join-Path $PSScriptRoot "..")
            if (-not $appendixResults) {
                Add-Issue "Appendix PDFs" "Appendix PDF tests failed" "One or more appendix PDF tests did not pass" "Error"
            }
        } catch {
            Add-Issue "Appendix PDFs" "Test execution failed" $_.Exception.Message "Error"
        }
    }
    
    # Test Linux compatibility
    Write-Host "Testing Linux compatibility..." -ForegroundColor Yellow
    try {
        # Linux compatibility script runs directly - capture its execution
        $linuxTestPath = Join-Path $PSScriptRoot (Join-Path "test" "test-linux-compatibility.ps1")
        $linuxResults = & $linuxTestPath
        # The script doesn't return a specific status, so we just note that it ran
        # Issues would be written via Add-Issue if the script used ReportIssues
    } catch {
        Add-Issue "Linux Compatibility" "Test execution failed" $_.Exception.Message "Error"
    }
    
    # Legacy core page tests (keeping for continuity)
    Write-Host "Testing core pages..." -ForegroundColor Yellow
    $corePageTests = @(
        @{ Url = "http://localhost:4000"; Name = "Homepage" },
        @{ Url = "http://localhost:4000/handbook"; Name = "Handbook page" },
        @{ Url = "http://localhost:4000/about"; Name = "About page" },
        @{ Url = "http://localhost:4000/events"; Name = "Events page" }
    )
    
    foreach ($test in $corePageTests) {
        try {
            $response = Invoke-WebRequest -Uri $test.Url -UseBasicParsing -TimeoutSec 10
            if ($response.StatusCode -ne 200) {
                Add-Issue "Core Pages" "$($test.Name) returned status $($response.StatusCode)" $test.Url "Error"
            }
        } catch {
            Add-Issue "Core Pages" "$($test.Name) failed to load" "$($test.Url) - $($_.Exception.Message)" "Error"
        }
    }
    
    # Generate consolidated issues report
    Write-ConsolidatedReport $IssuesFile
    
    # Report test results summary
    $errorCount = ($Global:AllIssues | Where-Object { $_.Severity -eq "Error" }).Count
    $warningCount = ($Global:AllIssues | Where-Object { $_.Severity -eq "Warning" }).Count
    
    Write-Host ""
    if ($Global:AllIssues.Count -eq 0) {
        Write-Host "PASS - All tests passed!" -ForegroundColor Green
        $failedTests = 0
    } else {
        Write-Host "COMPLETED - Found $($Global:AllIssues.Count) issues ($errorCount errors, $warningCount warnings)" -ForegroundColor $(if ($errorCount -gt 0) { "Red" } else { "Yellow" })
        Write-Host "Issues report: $IssuesFile" -ForegroundColor Cyan
        $failedTests = $errorCount  # Only count errors as failures
    }
} else {
    Write-Host "`nSkipping test suite" -ForegroundColor Yellow
    $failedTests = 0
}

# Final summary
$totalTime = (Get-Date) - $startTime
Write-Host @"

Build Summary
=============
Total time: $([Math]::Round($totalTime.TotalMinutes, 1)) minutes
Build type: $(if ($NoCache) { "Clean (no cache)" } else { "Incremental (cached)" })
Build order: PDF container first, then Jekyll
PDFs: $(if ($SkipPDFs) { "Skipped" } else { "Generated" })
Tests: $(if ($SkipTests) { "Skipped" } else { if ($failedTests -eq 0) { "PASS" } else { "Issues found ($failedTests errors)" } })
$(if (-not $SkipTests) { "Issues report: $IssuesFile" } else { "" })

Jekyll is running at: http://localhost:4000
Container status:
"@ -ForegroundColor Cyan

& $dockerComposeCmd.Split() ps

if ($failedTests -eq 0) {
    Write-Host "`nSUCCESS - Build completed successfully!" -ForegroundColor Green
    if (-not $SkipTests -and (Test-Path $IssuesFile)) {
        Write-Host "Issues report available for LLM review: $IssuesFile" -ForegroundColor Cyan
    }
    exit 0
} else {
    Write-Host "`nWARNING - Build completed with $failedTests error(s)" -ForegroundColor Yellow
    Write-Host "Review issues report for details: $IssuesFile" -ForegroundColor Cyan
    exit 1
}
